/*
 * Copyright (c) 2021-2025 Datalayer, Inc.
 *
 * MIT License
 */

/**
 * Insert block operation for Lexical documents
 *
 * @module tools/core/operations/insertBlock
 */

import type {
  ToolOperation,
  LexicalExecutionContext,
} from '../core/interfaces';
import type { LexicalBlock } from '../core/types';
import { formatResponse } from '../core/formatter';

/**
 * Parameters for inserting a block into a Lexical document
 */
export interface InsertBlockParams {
  /**
   * Insert after block with id given by afterId
   * Use 'TOP' to insert at beginning or 'BOTTOM' to append at end
   * Block IDs are stable identifiers that persist across document changes
   */
  afterId: string;

  /**
   * Block type (e.g., "paragraph", "heading", "code", "quote", "jupyter-cell")
   */
  type: string;

  /**
   * Block content/source text
   * For code blocks and jupyter-cells, this is the code
   * For paragraphs/headings, this is the text
   */
  source: string;

  /**
   * Optional metadata object
   * e.g., { level: 1 } for headings, { language: "python" } for code
   */
  properties?: Record<string, unknown>;
}

/**
 * Result of inserting a block
 */
export interface InsertBlockResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Error message if operation failed */
  error?: string;
}

/**
 * Validates InsertBlockParams at runtime.
 */
function isInsertBlockParams(params: unknown): params is InsertBlockParams {
  if (typeof params !== 'object' || params === null) {
    return false;
  }

  const p = params as Record<string, unknown>;

  // Validate required fields
  if (
    typeof p.afterId !== 'string' ||
    typeof p.type !== 'string' ||
    typeof p.source !== 'string'
  ) {
    return false;
  }

  // Validate optional fields
  if (
    p.properties !== undefined &&
    (typeof p.properties !== 'object' || p.properties === null)
  ) {
    return false;
  }

  return true;
}

/**
 * Insert block operation - adds a new block to a Lexical document
 *
 * Supports inserting various block types:
 * - paragraph: Regular text paragraph
 * - heading: Heading block (specify tag: h1-h6 in properties)
 * - code: Code block (specify language in properties)
 * - quote: Blockquote
 * - list/listitem: List blocks
 */
export const insertBlockOperation: ToolOperation<
  InsertBlockParams,
  InsertBlockResult
> = {
  name: 'insertBlock',

  async execute(
    params: unknown,
    context: LexicalExecutionContext,
  ): Promise<InsertBlockResult> {
    // Validate params using type guard
    if (!isInsertBlockParams(params)) {
      throw new Error(
        `Invalid parameters for insertBlock. Expected { afterId: string, type: string, source: string, properties?: object }. ` +
          `Received: ${JSON.stringify(params)}`,
      );
    }

    // Now TypeScript knows params is InsertBlockParams!
    const { afterId, type, source, properties } = params;
    const { lexicalId } = context;

    // Validate context
    if (!lexicalId) {
      throw new Error(
        'Lexical ID is required for insertBlock operation. ' +
          'Ensure the tool execution context includes a valid lexicalId.',
      );
    }

    // Ensure executeCommand is available
    if (!context.executeCommand) {
      throw new Error(
        'executeCommand callback is required for insertBlock operation.',
      );
    }

    try {
      // Build block data using Jupyter-aligned format
      const block: LexicalBlock = {
        block_id: '', // Will be generated by Lexical when inserted
        block_type: type,
        source: source,
        metadata: properties || {},
      };

      // Call internal command with URI (VS Code-specific requirement)
      await context.executeCommand('lexical.insertBlock', {
        lexicalId,
        block,
        afterBlockId: afterId,
      });

      return formatResponse(
        {
          success: true,
        },
        context.format,
      ) as InsertBlockResult;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      throw new Error(`Failed to insert block: ${errorMessage}`);
    }
  },
};
