/*
 * Copyright (c) 2021-2023 Datalayer, Inc.
 *
 * MIT License
 */

/**
 * Insert multiple blocks operation for Lexical documents
 *
 * @module tools/core/operations/insertBlocks
 */

import type {
  ToolOperation,
  LexicalExecutionContext,
} from '../core/interfaces';
import type { LexicalBlock } from '../core/types';
import { formatResponse } from '../core/formatter';

/**
 * A block to be inserted in batch operation
 */
export interface BlockData {
  /**
   * Block type (e.g., "paragraph", "heading", "code", "quote", "jupyter-cell")
   */
  type: string;

  /**
   * Block content/source text (Jupyter-aligned naming)
   * For code blocks and jupyter-cells, this is the code
   * For paragraphs/headings, this is the text
   */
  source: string;

  /**
   * Optional metadata object
   * e.g., { level: 1 } for headings, { language: "python" } for code
   */
  properties?: Record<string, unknown>;
}

/**
 * Parameters for inserting multiple blocks into a Lexical document
 */
export interface InsertBlocksParams {
  /**
   * Insert first block after this block ID (from readBlocks result)
   * Subsequent blocks are inserted after the previous one
   * Use 'TOP' to insert at beginning or 'BOTTOM' to append at end
   * Block IDs are stable identifiers that persist across document changes
   */
  afterId: string;

  /**
   * Array of blocks to insert
   */
  blocks: BlockData[];
}

/**
 * Result of inserting multiple blocks
 */
export interface InsertBlocksResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Error message if operation failed */
  error?: string;

  /** Number of blocks successfully inserted */
  insertedCount?: number;
}

/**
 * Validates InsertBlocksParams at runtime.
 */
function isInsertBlocksParams(params: unknown): params is InsertBlocksParams {
  if (typeof params !== 'object' || params === null) {
    return false;
  }

  const p = params as Record<string, unknown>;

  // Validate required fields
  if (typeof p.afterId !== 'string') {
    return false;
  }

  if (!Array.isArray(p.blocks)) {
    return false;
  }

  // Validate each block in the array
  for (const block of p.blocks) {
    if (typeof block !== 'object' || block === null) {
      return false;
    }
    const b = block as Record<string, unknown>;
    if (typeof b.type !== 'string' || typeof b.source !== 'string') {
      return false;
    }
    if (
      b.properties !== undefined &&
      (typeof b.properties !== 'object' || b.properties === null)
    ) {
      return false;
    }
  }

  return true;
}

/**
 * Insert multiple blocks operation - adds multiple blocks to a Lexical document in one transaction
 *
 * More efficient than calling insertBlock multiple times.
 * Blocks are inserted sequentially, each after the previous one.
 *
 * Uses lexicalId as the universal identifier (matches Lexical component).
 */
export const insertBlocksOperation: ToolOperation<
  InsertBlocksParams,
  InsertBlocksResult
> = {
  name: 'insertBlocks',

  async execute(
    params: unknown,
    context: LexicalExecutionContext,
  ): Promise<InsertBlocksResult> {
    // Validate params using type guard
    if (!isInsertBlocksParams(params)) {
      throw new Error(
        `Invalid parameters for insertBlocks. Expected { afterId: string, blocks: Array<{ type: string, source: string, properties?: object }> }. ` +
          `Received: ${JSON.stringify(params)}`,
      );
    }

    // Now TypeScript knows params is InsertBlocksParams!
    const { afterId, blocks } = params;
    const { lexicalId } = context;

    // Validate context
    if (!lexicalId) {
      throw new Error(
        'Lexical ID is required for insertBlocks operation. ' +
          'Ensure the tool execution context includes a valid lexicalId.',
      );
    }

    // Ensure executeCommand is available
    if (!context.executeCommand) {
      throw new Error(
        'executeCommand callback is required for insertBlocks operation.',
      );
    }

    try {
      // Convert to LexicalBlock format
      const lexicalBlocks: LexicalBlock[] = blocks.map(b => ({
        block_id: '', // Will be generated by Lexical when inserted
        block_type: b.type,
        source: b.source,
        metadata: b.properties || {},
      }));

      // Call internal command with URI (VS Code-specific requirement)
      await context.executeCommand('lexical.insertBlocks', {
        lexicalId,
        blocks: lexicalBlocks,
        afterBlockId: afterId,
      });

      return formatResponse(
        {
          success: true,
          insertedCount: lexicalBlocks.length,
        },
        context.format,
      ) as InsertBlocksResult;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      throw new Error(`Failed to insert blocks: ${errorMessage}`);
    }
  },
};
