header:
  license:
    spdx-id: MIT
    copyright-owner: Datalayer, Inc.
    copyright-year: 2021-2023
    content: |
      Copyright (c) [year] [owner]

      MIT License

  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.tsbuildinfo'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/MANIFEST.in'
    - '**/static'
    - '**/typings'
    - '**/schemas'
    - '**/themes'
    - '*.map.js'
    - '*.bundle.js'
    - '**/.*'
    - 'LICENSE'
    - '.devcontainer/resources/'
    - 'dev/notebooks/example1.dash'
    - 'dev/notebooks/subfolder-2/untitled.txt'
    - 'examples/cra/public/robots.txt'
    - '**/LICENSE.txt'
    - '**/*.nblink'
    - 'docs/docs'
    - 'packages/lexical/src/ui/PrettierButton.tsx_tmp'
    - 'packages/react/third-party-license.txt'
    - 'patches/'
    - '**/robots.txt'
    - '.husky/_/applypatch-msg'
    - '.husky/_/commit-msg'
    - '.husky/_/h'
    - '.husky/_/post-applypatch'
    - '.husky/_/post-checkout'
    - '.husky/_/post-commit'
    - '.husky/_/post-merge'
    - '.husky/_/post-rewrite'
    - '.husky/_/pre-applypatch'
    - '.husky/_/pre-auto-gc'
    - '.husky/_/pre-commit'
    - '.husky/_/pre-merge-commit'
    - '.husky/_/pre-push'
    - '.husky/_/pre-rebase'
    - '.husky/_/prepare-commit-msg'
    - '.husky/pre-commit'
    - '**/*.disabled'
    - '**/*.lexical'

  comment: on-failure
