header:
  license:
    spdx-id: MIT
    copyright-owner: Datalayer, Inc.
    copyright-year: 2021-2023
    content: |
      Copyright (c) [year] [owner]

      MIT License

  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.tsbuildinfo'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/MANIFEST.in'
    - '**/static'
    - '**/typings'
    - '**/schemas'
    - '**/themes'
    - '*.map.js'
    - '*.bundle.js'
    - '**/.*'
    - 'LICENSE'
    - '.devcontainer/resources/'
    - 'dev/notebooks/example1.dash'
    - 'dev/notebooks/subfolder-2/untitled.txt'
    - 'examples/cra/public/robots.txt'
    - '**/LICENSE.txt'
    - '**/*.nblink'
    - 'docs/docs'
    - 'packages/lexical/src/ui/PrettierButton.tsx_tmp'
    - 'packages/react/third-party-license.txt'
    - 'patches/'
    - '**/robots.txt'

  comment: on-failure