enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      js-yaml: "*"
      rimraf: "*"
    peerDependencies:
      nx: "*"
