# Copyright (c) 2021-2023 Datalayer, Inc.
#
# MIT License

# This file is auto-generated by Hatchling. As such, do not:
#   - modify
#   - track in version control e.g. be sure to add to .gitignore
__version__ = VERSION = '0.1.1'
