# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

enableImmutableInstalls: false
enableInlineBuilds: false
enableTelemetry: false
httpTimeout: 60000
nodeLinker: node-modules
npmRegistryServer: "https://registry.yarnpkg.com"

# This will fix the build error with @lerna/legacy-package-management
# See https://github.com/lerna/repro/pull/11
packageExtensions:
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      "js-yaml": "*"
      "rimraf": "*"
    peerDependencies:
      "nx": "*"
